### ISSUE TITLE
ES 2.x support

### ISSUE THREAD

**Issue by adepretis** [rtoma/logspout-redis-logstash#11]
With ES 2.x field names can no longer contain dots - also see:

https://github.com/looplab/logspout-logstash/issues/11
https://github.com/elastic/elasticsearch/issues/14594

When using e.g. Rancher, which heavily uses labels with dots, logspout-redis-logstash totally breaks down on a Rancher host.

Unfortunately I don't know Go that well, so I can't create a PR :-(

**Comment by rtoma** [comment]
Thank you for creating this issue. I am aware of this situation.

I am currently fixing this by de-dotting the Docker labels in Logstash. A better option would be to dedot the labels in Logspout by replacing them with underscores.

Quietly I am hoping Elastic will re-add support for dots in fieldnames.

Feel free to learn Go and submit a pull request for replacing the dots.

**Comment by adepretis** [comment]
Are you using the Logstash de_dot plugin? - maybe you want to share your Logstash de-dotting configuration for others here? ;-)
