### ISSUE TITLE
Splitting of image and tag if registry with part is present but no tag

### ISSUE THREAD

**Issue by pgrund** [rtoma/logspout-redis-logstash#6]
Hi,
thanks for the image.

I found a small issue considering splitImage function.
Wwhen using `my.registry.host:443/path/to/image` as **image** name I would expect **image** being `my.registry.host:443/path/to/image` and tag being empty

see #5

**Comment by rtoma** [comment]
Merged. Thanks!
Feel free to push a 2nd PR to use 'latest' as default tag.
